#!/bin/bash
#set -x #echo on
#set +x #echo off
#do_echo=1 # Echo the commands
do_echo=0 # Don't echo the commands
#do_run=1 # Execute(evaluate) the commands
do_run=0 # Don't evaluate any commands : can be overridden with -f
do_sapcp_stuff=1 #Requires current sapcp login
do_entitle_stuff=1 #Requires current sapcp login
do_perm_stuff=1 #Requires mitmproxy in "Ready for Batch Operations!" state
do_cf_stuff=1 #Requires current cf login
force=$2

#GLOBAL VALUES
globalacctsubdomain="partner-eng"
hanacloudorg="partner-eng-hca"
hanacloudspace="prod"
hanacloudspaceguid="d096c374-91ef-4e57-aef6-8088384b9bc0"
hanaclouddbinstguid="ffa845c4-c70e-4774-ba37-c0a6fdf16850"
cloudfoundryuser="andrew.lunde@sap.com"
relativepathtomtar="../mta_archives/acc.mtar"

if [ "$#" -eq 2 ]; then
  if [ $force == "-f" ]; then
    do_run=1
    echo ""
    echo "Forcing command execution"
    echo ""
  fi
fi

orgcnt=0
START="$(date +%s)"

while read orgspace
do

first=1
IFS=':'     # colon (:) is set as delimiter
read -ra ADDR <<< "$orgspace"   # str is read into an array as tokens separated by IFS
for i in "${ADDR[@]}"; do   # access each element of array
    #echo "$i"
    #echo $first
    if [ $first -eq 1 ]; then
	    first=0
	    org=$i
    else
	    first=1
	    space=$i
    fi
done
IFS=' '     # reset to default value after usage

#https://accounts-service.cfapps.eu10.hana.ondemand.com/api#/

if [ $do_sapcp_stuff -eq 1 ]; then 
echo "================================================"
echo "Creating SubAccount : $org "
cmd='lastsubguid=$(sapcp --format json create accounts/subaccount --global-account '$globalacctsubdomain' --display-name '$org' --region us21 --subdomain viasapcp'$orgcnt' --used-for-production NOT_USED_FOR_PRODUCTION --description "Azure subaccount" --beta-enabled | jq .guid | tr -ds '"'"'"'"'"' '"'"''"'"')'
if [ $do_echo -eq 1 ]; then echo $cmd; fi
if [ $do_run -eq 1 ]; then eval $cmd; fi
echo ""

if [ $do_run -eq 1 ]; then 
  echo "LastSubGUID = "$lastsubguid

  state=INIT
  while [ $state != "OK" ] && [ $lastsubguid != "null" ]; do
    echo "State is "$state
    sleep 2
    state=$(sapcp --format json get accounts/subaccount $lastsubguid | jq .state | tr -ds '"' '')
  done
fi

#https://provisioning-service.cfapps.eu10.hana.ondemand.com/api#/

#https://accounts-service.cfapps.eu10.hana.ondemand.com/api#/
# sapcp create accounts/environment-instance --subaccount c96d49c7-bdbf-436c-a35a-322b90ba2793 --parameters '{"instance_name":"ypartner-sub1","users":[{"email":"'$cloudfoundryuser'"}]}' --display-name ypartner-sub1 --environment cloudfoundry --landscape cf-us21 --service cloudfoundry --plan standard
echo "Enabling CF in : $org "
#cmd='lastguid=$(curl $accountsurlcen/accounts/v1/subaccounts --silent --location --insecure --request POST --header '"'"'Content-Type: application/json'"'"' --header '"'"'Accept: application/json'"'"' --header '"'"'Authorization: Bearer '"'"'$bearercen --data-raw '"'"'{"betaEnabled": true, "customProperties": [ { "key": "creator", "value": "'$sapcpuser'" } ], "description": "Subaccount created via API", "displayName": "'$org'", "parentGUID": "'"'"'$globalacctguid'"'"'", "region": "us21", "subaccountAdmins": [ "andrew.lunde@sap.com" ], "subdomain": "viaapi'$orgcnt'", "usedForProductionSetting": "USED_FOR_PRODUCTION"}'"'"' | jq .guid | tr -ds '"'"'"'"'"' '"'"''"'"')'

cmd='lastenvguid=$(sapcp --format json create accounts/environment-instance --subaccount '$lastsubguid' --parameters '"'"'{"instance_name":"'$org'","users":[{"email":"'$cloudfoundryuser'"}]}'"'"' --display-name '$org' --environment cloudfoundry --landscape cf-us21 --service cloudfoundry --plan standard | jq .id | tr -ds '"'"'"'"'"' '"'"''"'"')'
if [ $do_echo -eq 1 ]; then echo $cmd; fi
if [ $do_run -eq 1 ]; then eval $cmd; fi
echo ""

if [ $do_run -eq 1 ]; then 
  echo "LastEnvGUID = "$lastenvguid

  status=INIT
  while [ $status != "Processed" ] && [ $lastenvguid != "null" ]; do
    echo "Status is "$status
    sleep 2
    status=$(sapcp --format json  get accounts/environment-instance $lastenvguid --subaccount $lastsubguid | jq .status | tr -ds '"' '')
  done
fi

fi

if [ $do_entitle_stuff -eq 1 ]; then 

echo "Entitling : $org "
echo ""

# Now allocate application runtime and hana/schema quotas

cmd='sapcp --format json assign accounts/entitlement --global-account '$globalacctsubdomain' --to-subaccount '$lastsubguid' --for-service hana --plan schema --enable'
if [ $do_echo -eq 1 ]; then echo $cmd; fi
if [ $do_run -eq 1 ]; then eval $cmd; fi

cmd='sapcp --format json assign accounts/entitlement --global-account '$globalacctsubdomain' --to-subaccount '$lastsubguid' --for-service APPLICATION_RUNTIME --plan MEMORY --amount 1'
if [ $do_echo -eq 1 ]; then echo $cmd; fi
if [ $do_run -eq 1 ]; then eval $cmd; fi

fi

if [ $do_cf_stuff -eq 1 ]; then 

cmd='cf target -o '$org
if [ $do_echo -eq 1 ]; then echo $cmd; fi
if [ $do_run -eq 1 ]; then eval $cmd; sleep 1; fi

cmd='cf create-space '$space
if [ $do_echo -eq 1 ]; then echo $cmd; fi
if [ $do_run -eq 1 ]; then eval $cmd; sleep 1; fi

cmd='cf target -s '$space
if [ $do_echo -eq 1 ]; then echo $cmd; fi
if [ $do_run -eq 1 ]; then eval $cmd; sleep 1; fi

cmd='lastorgguid=$(cf org '$org' --guid)'
if [ $do_echo -eq 1 ]; then echo $cmd; fi
if [ $do_run -eq 1 ]; then eval $cmd; fi


cmd='lastspaceguid=$(cf space '$space' --guid)'
if [ $do_echo -eq 1 ]; then echo $cmd; fi
if [ $do_run -eq 1 ]; then eval $cmd; fi

cmd='cf target -o '$hanacloudorg' -s '$hanacloudspace
if [ $do_echo -eq 1 ]; then echo $cmd; fi
if [ $do_run -eq 1 ]; then eval $cmd; sleep 1; fi

# Now go permit HANA in this space.
# This is not WORKING emulate UI instead
#cmd='cf update-service pehcaza -c '"'"'{"operation":"adddatabasemapping", "orgid":"'$lastorgguid'", "spaceid":"'$lastspaceguid'"}'"'"''
#echo $cmd
#if [ $do_run -eq 1 ]; then eval $cmd; fi

#echo "Giving the update a couple secs."
#sleep 2

fi

if [ $do_perm_stuff -eq 1 ]; then 


#cmd='cf service pehcaza'
#echo $cmd
#if [ $do_run -eq 1 ]; then eval $cmd; fi

#cmd='lastguid=$(curl $accountsurlcen/accounts/v1/subaccounts --silent --location --insecure --request POST --header '"'"'Content-Type: application/json'"'"' --header '"'"'Accept: application/json'"'"' --header '"'"'Authorization: Bearer '"'"'$bearercen --data-raw '"'"'{"betaEnabled": true, "customProperties": [ { "key": "creator", "value": "'$sapcpuser'" } ], "description": "Subaccount created via API", "displayName": "'$org'", "parentGUID": "'"'"'$globalacctguid'"'"'", "region": "us21", "subaccountAdmins": [ "andrew.lunde@sap.com" ], "subdomain": "viaapi'$orgcnt'", "usedForProductionSetting": "USED_FOR_PRODUCTION"}'"'"' | jq .guid | tr -ds '"'"'"'"'"' '"'"''"'"')'
cmd='lastmappingid=$(curl https://hana-cockpit.cfapps.us21.hana.ondemand.com/hana-inventory/sap/hana/cloud/inventory/api/v1/spaces/'$hanacloudspaceguid'/hana/'$hanaclouddbinstguid'/mappings -x localhost:8080 --silent --location --insecure --request PUT --header '"'"'Content-Type: application/json'"'"' --data-raw '"'"'{"database_id": "'$hanaclouddbinstguid'", "organization_guid": "'$lastorgguid'", "space_guid": "'$lastspaceguid'"}'"'"' | jq .guid | tr -ds '"'"'"'"'"' '"'"''"'"')'
if [ $do_echo -eq 1 ]; then echo $cmd; fi
if [ $do_run -eq 1 ]; then eval $cmd; fi

fi

if [ $do_cf_stuff -eq 1 ]; then 

cmd='cf target -o '$org' -s '$space
if [ $do_echo -eq 1 ]; then echo $cmd; fi
if [ $do_run -eq 1 ]; then eval $cmd; fi

echo Deploying into $org $space

cmd='cf deploy '$relativepathtomtar' -f'
if [ $do_echo -eq 1 ]; then echo $cmd; fi
if [ $do_run -eq 1 ]; then eval $cmd; fi

fi

((orgcnt++))

done < $1

DURATION=$[ $(date +%s) - ${START} ]

echo "================================================"
echo $orgcnt orgs processed in ${DURATION} seconds = $(( ${DURATION} / $orgcnt )) secs/org