#!/bin/bash
#do_run=1 # Execute(evaluate) the commands
do_run=0 # Don't evaluate any commands
do_this=0
force=$2
if [ "$#" -eq 2 ]; then
  if [ $force == "-f" ]; then
    do_run=1
    echo ""
    echo "Forcing command execution"
    echo ""
  fi
fi

orgcnt=0
START="$(date +%s)"

while read orgspace
do

first=1
IFS=':'     # colon (:) is set as delimiter
read -ra ADDR <<< "$orgspace"   # str is read into an array as tokens separated by IFS
for i in "${ADDR[@]}"; do   # access each element of array
    #echo "$i"
    #echo $first
    if [ $first -eq 1 ]; then
	    first=0
	    org=$i
    else
	    first=1
	    space=$i
    fi
done
IFS=' '     # reset to default value after usage

#https://accounts-service.cfapps.eu10.hana.ondemand.com/api#/
#curl $accountsurl/accounts/v1/subaccounts --silent --location --insecure --request POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer '$bearer --data-raw '{"betaEnabled": true, "customProperties": [ { "key": "creator", "value": "primaryuser03" } ], "description": "Subaccount created via API", "displayName": "ViaAPI", "parentGUID": "'$globalacctguid'", "region": "us21", "subaccountAdmins": [ "andrew.lunde@sap.com" ], "subdomain": "viaapi", "usedForProductionSetting": "USED_FOR_PRODUCTION"}' | jq .


if [ $do_this -eq 1 ]; then 
echo "Creating SubAccount : $org "
cmd='lastguid=$(curl $accountsurlcen/accounts/v1/subaccounts --silent --location --insecure --request POST --header '"'"'Content-Type: application/json'"'"' --header '"'"'Accept: application/json'"'"' --header '"'"'Authorization: Bearer '"'"'$bearercen --data-raw '"'"'{"betaEnabled": true, "customProperties": [ { "key": "creator", "value": "'$sapcpuser'" } ], "description": "Subaccount created via API", "displayName": "'$org'", "parentGUID": "'"'"'$globalacctguid'"'"'", "region": "us21", "subaccountAdmins": [ "andrew.lunde@sap.com" ], "subdomain": "viaapi'$orgcnt'", "usedForProductionSetting": "USED_FOR_PRODUCTION"}'"'"' | jq .guid | tr -ds '"'"'"'"'"' '"'"''"'"')'

echo $cmd
if [ $do_run -eq 1 ]; then eval $cmd; fi
echo ""

echo "LastGUID = "$lastguid

if [ $do_run -eq 1 ]; then 
  state=INIT
  while [ $state != "OK" ] && [ $lastguid != "null" ]; do
    echo "State is "$state
    sleep 2
    state=$(curl $accountsurlcen/accounts/v1/subaccounts/$lastguid --silent --location --insecure --header 'Content-Type: application/json' --header 'Authorization: Bearer '$bearercen | jq .state | tr -ds '"' '')
  done
fi

#https://provisioning-service.cfapps.eu10.hana.ondemand.com/api#/

#space=dev
#echo "Creating Space : $space in $org"
#cmd='cf create-space '$space' -o '$org''
#echo $cmd
#if [ $do_run -eq 1 ]; then eval $cmd; fi
#echo ""

#https://accounts-service.cfapps.eu10.hana.ondemand.com/api#/
# sapcp create accounts/environment-instance --subaccount c96d49c7-bdbf-436c-a35a-322b90ba2793 --parameters '{"instance_name":"ypartner-sub1","users":[{"email":"andrew.lunde@sap.com"}]}' --display-name ypartner-sub1 --environment cloudfoundry --landscape cf-us21 --service cloudfoundry --plan standard
echo "Enabling CF in : $org "
#cmd='lastguid=$(curl $accountsurlcen/accounts/v1/subaccounts --silent --location --insecure --request POST --header '"'"'Content-Type: application/json'"'"' --header '"'"'Accept: application/json'"'"' --header '"'"'Authorization: Bearer '"'"'$bearercen --data-raw '"'"'{"betaEnabled": true, "customProperties": [ { "key": "creator", "value": "'$sapcpuser'" } ], "description": "Subaccount created via API", "displayName": "'$org'", "parentGUID": "'"'"'$globalacctguid'"'"'", "region": "us21", "subaccountAdmins": [ "andrew.lunde@sap.com" ], "subdomain": "viaapi'$orgcnt'", "usedForProductionSetting": "USED_FOR_PRODUCTION"}'"'"' | jq .guid | tr -ds '"'"'"'"'"' '"'"''"'"')'

sapcp create accounts/environment-instance --subaccount $lastguid --parameters '{"instance_name":"'$org'","users":[{"email":"andrew.lunde@sap.com"}]}' --display-name $org --environment cloudfoundry --landscape cf-us21 --service cloudfoundry --plan standard

#echo $cmd
#if [ $do_run -eq 1 ]; then eval $cmd; fi
#echo ""

#echo "LastGUID = "$lastguid
#
#if [ $do_run -eq 1 ]; then 
#  state=INIT
#  while [ $state != "OK" ] && [ $lastguid != "null" ]; do
#    echo "State is "$state
#    sleep 2
#    state=$(curl $accountsurlcen/accounts/v1/subaccounts/$lastguid --silent --location --insecure --header 'Content-Type: application/json' --header 'Authorization: Bearer '$bearercen | jq .state | tr -ds '"' '')
#  done
#fi

sleep 15

cf t -o $org

sleep 1

cf create-space dev

sleep 2

cf t -s dev

sleep 1
fi


# Now allocate application runtime and hana/schema quotas

# Now go permit HANA in this space.

echo Deploying into $org

cf t -o $org -s dev

cf deploy ../mta_archives/acc.mtar -f

#sleep 60

((orgcnt++))

done < $1

DURATION=$[ $(date +%s) - ${START} ]

echo $orgcnt orgs processed in ${DURATION} seconds = $(( ${DURATION} / $orgcnt )) secs/org